language: scala

script: sbt stage

env:
  global:
    - secure: "gSA1+PfRHUyW/3Zc/whVxBEVWyjIjPMzWT5LaQ4cN5fkhZEN/bB60aSSoFcq50qpajLS4T97c66/NSXlFHji7B1cXSeS473IXDSf5cWPyq5G+PkBJaZCgvuGZhf94lgxWcSTB/B0Vid7OWxO6gxeFXntt4PiNbzGEHqdXvqKzkJu07Lp+8EcXszNAR13iC469QFqmv4y26mhbz9yYOxM1TSbG4SCestZ4W0wLCQxC9ygn5yOBSW5ZGCMnpUPq14e8LndbxhuYXVoJ61SNLP0a/fjmrGalwB8dgCJG63tdzZdD72Kdh8OZ2l0k+BS4bamg2lRQpX0f+Y3FnjIqRLqKBVHMfhsi0DbsSTtOOH4JqpXUwyvMQLNWoEvNZ+07mxDFfM7yvYKsS9ms2S/X6+JnnvAM2ZYr50GVSpn7V1/tRsIwUmWUn4dV8UYENgAsviya9I0DagGdE7cF0n755ZFKWq3jvG0W+OX+mNBnqLiQOnEIqukApGr+cLT4jk3cMj7v+4LPeYtsVGdbcgVyH/n8E4lIUJk3pOYyn2HJFmOjzdmEw8Vb088nBH6F4z1SSJzajfK04BmDlv5FQ+wa/CQAAOZB6uvhfK+W4K8efkriUxnfLPKnVTGYnvEOurodPFIqxf4R7Uax3xTjz7XsbB4EN6BuWwy18NxNC0DuIKVwPo="

after_success: sbt deployHeroku